name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          
      - name: Install dependencies
        run: bun install --frozen-lockfile
        
      - name: Run linting
        run: bun run check
        
      - name: Run type checking  
        run: bun run typecheck
        
      - name: Run tests
        run: bun run test
        
      - name: Build project
        run: bun run build
        
      - name: Test CLI execution
        run: |
          node dist/index.js --help
          node dist/index.js scan --help